sudo: required
services:
  - docker 

before_install:
  - docker build -t bird5555/docker-react -f Dockerfile.dev .

script:
  - docker run bird5555/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk  
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-888771398899"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key-id: $AWS_ACCESS_KEY  
  secret-access_key:
    secure: "$AWS_SECRET_KEY"

